apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rollout.yaml
  - analysis-template.yaml
components:
  - ../../../components/accounts
  - ../../../../components/backend-service
